version: '3.8'

services:
  python:
    build: .                     # ← Dockerfile からビルドする場合は必須
    volumes:
      - .:/app                   # ← ソースコードをリアルタイム反映（学習向き）
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app                    # ← .envの環境変数をコンテナ内に渡す
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
    ports:
      - "8888:8888"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
